=== RuiNeto015/rest_api/xsd/familyTypes.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http//estg.ipp.pt/familyTypes" targetNamespace="http//estg.ipp.pt/familyTypes" elementFormDefault="qualified">

    <xs:element name="family" type="familyType" />

    <xs:complexType name="familyType">
        <xs:sequence>
            <xs:element name="numberOfElements" type="numberOfElementsType" />
            <xs:element name="country" type="xs:string" />
            <xs:element name="city" type="xs:string" />
            <xs:element name="contacts" type ="contactsType"></xs:element>
            <xs:element name="members" type="membersType" />
            <xs:element name="datePreferences" type="datePreferencesType" />
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="numberOfElementsType">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="2" />
            <xs:maxInclusive value="7" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="datePreferencesType">
        <xs:sequence>
            <xs:element name="datePreference" type="dateType" minOccurs="1" maxOccurs="5" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="membersType">
        <xs:sequence>
            <xs:element name="member" type="memberType" minOccurs="2" maxOccurs="7" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="memberType">
        <xs:sequence>
            <xs:element name="name" type="nameType" />
            <xs:element name="birthdayDate" type="dateType" />
            <xs:element name="genre" type="genreType" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="contactsType">
        <xs:sequence>
            <xs:element name="phoneNumber" type="phoneNumberType" />
            <xs:element name="email" type="emailType" />
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="indicativeType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[+]+[0-9-]*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="phoneNumberType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="indicative" type="indicativeType" use="required" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="emailType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[^@]+@[^\.]+\..+" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="genreType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="masculine" />
            <xs:enumeration value="feminine" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="nameType">
        <xs:sequence>
            <xs:element name="firstName" type="xs:string" />
            <xs:element name="lastName" type="xs:string" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="dateType">
        <xs:simpleContent>
            <xs:extension base="xs:date">
                <xs:attribute name="format" type="xs:string" fixed="yyyy-mm-dd" use="required" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

</xs:schema>

=== RuiNeto015/rest_api/XMLExamples/example_4.xml
<?xml version="1.0" encoding="UTF-8"?>

<family xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xmlns="http//estg.ipp.pt/familyTypes" 
xsi:schemaLocation="http//estg.ipp.pt/familyTypes familyTypes.xsd">

    <numberOfElements>2</numberOfElements>
    <country>Greenland</country>
    <city>Tasiilaq</city>
    <contacts>
        <phoneNumber indicative="+521">256745698</phoneNumber>
        <email>johngroove@gmail.com</email>
    </contacts>
    <members>
        <member>
            <name>
                <firstName>John</firstName>
                <lastName>Groove</lastName>
            </name>
            <birthdayDate format="yyyy-mm-dd">1998-09-14</birthdayDate>
            <genre>masculine</genre>
        </member>
        <member>
            <name>
                <firstName>Matthia</firstName>
                <lastName>Groove</lastName>
            </name>
            <birthdayDate format="yyyy-mm-dd">2001-12-14</birthdayDate>
            <genre>feminine</genre>
        </member>
    </members>
    <datePreferences>
        <datePreference format="yyyy-mm-dd">2021-12-13</datePreference>
        <datePreference format="yyyy-mm-dd">2021-12-15</datePreference>   
    </datePreferences>
</family>

=== RuiNeto015/rest_api/XMLExamples/example_2.xml
<?xml version="1.0" encoding="UTF-8"?>

<family xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xmlns="http//estg.ipp.pt/familyTypes" 
xsi:schemaLocation="http//estg.ipp.pt/familyTypes familyTypes.xsd">

    <numberOfElements>2</numberOfElements>
    <country>Iceland</country>
    <city>Akranes</city>
    <contacts>
        <phoneNumber indicative="+999">239658975</phoneNumber>
        <email>nathangarrity@gmail.com</email>
    </contacts>
    <members>
        <member>
            <name>
                <firstName>Nathan</firstName>
                <lastName>Garrity</lastName>
            </name>
            <birthdayDate format="yyyy-mm-dd">1960-09-14</birthdayDate>
            <genre>masculine</genre>
        </member>
        <member>
            <name>
                <firstName>Joana</firstName>
                <lastName>Garrity</lastName>
            </name>
            <birthdayDate format="yyyy-mm-dd">1965-12-14</birthdayDate>
            <genre>feminine</genre>
        </member>
    </members>
    <datePreferences>
        <datePreference format="yyyy-mm-dd">2021-12-22</datePreference> 
    </datePreferences>
</family>

=== RuiNeto015/rest_api/XMLExamples/example_1.xml
<?xml version="1.0" encoding="UTF-8"?>

<family xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http//estg.ipp.pt/familyTypes" xsi:schemaLocation="http//estg.ipp.pt/familyTypes familyTypes.xsd">

    <numberOfElements>2</numberOfElements>
    <country>Spain</country>
    <city>Sevilha</city>
    <contacts>
        <phoneNumber indicative="+351">914672073</phoneNumber>
        <email>abc@gmail.com</email>
    </contacts>
    <members>
        <member>
            <name>
                <firstName>Rui</firstName>
                <lastName>Neto</lastName>
            </name>
            <birthdayDate format="yyyy-mm-dd">2002-02-20</birthdayDate>
            <genre>masculine</genre>
        </member>
        <member>
            <name>
                <firstName>Sofia</firstName>
                <lastName>Neto</lastName>
            </name>
            <birthdayDate format="yyyy-mm-dd">1999-10-23</birthdayDate>
            <genre>feminine</genre>
        </member>
    </members>
    <datePreferences>
        <datePreference format="yyyy-mm-dd">2021-09-19</datePreference>
        <datePreference format="yyyy-mm-dd">2021-09-20</datePreference>
        <datePreference format="yyyy-mm-dd">2021-09-21</datePreference>
    </datePreferences>
</family>

=== RuiNeto015/rest_api/XMLExamples/example_5.xml
<?xml version="1.0" encoding="UTF-8"?>

<family xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xmlns="http//estg.ipp.pt/familyTypes" 
xsi:schemaLocation="http//estg.ipp.pt/familyTypes familyTypes.xsd">

    <numberOfElements>2</numberOfElements>
    <country>Madagascar</country>
    <city>Mahajanga</city>
    <contacts>
        <phoneNumber indicative="+339">199876900</phoneNumber>
        <email>zaynetemalik@gmail.com</email>
    </contacts>
    <members>
        <member>
            <name>
                <firstName>Zaynete</firstName>
                <lastName>Malik</lastName>
            </name>
            <birthdayDate format="yyyy-mm-dd">1995-02-02</birthdayDate>
            <genre>masculine</genre>
        </member>
        <member>
            <name>
                <firstName>Martin</firstName>
                <lastName>Garrix</lastName>
            </name>
            <birthdayDate format="yyyy-mm-dd">1993-11-05</birthdayDate>
            <genre>masculine</genre>
        </member>
    </members>
    <datePreferences>
        <datePreference format="yyyy-mm-dd">2021-10-04</datePreference>  
    </datePreferences>
</family>

=== RuiNeto015/rest_api/XMLExamples/example_3.xml
<?xml version="1.0" encoding="UTF-8"?>

<family xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xmlns="http//estg.ipp.pt/familyTypes" 
xsi:schemaLocation="http//estg.ipp.pt/familyTypes familyTypes.xsd">

    <numberOfElements>2</numberOfElements>
    <country>Iceland</country>
    <city>Grindavik</city>
    <contacts>
        <phoneNumber indicative="+999">726389467</phoneNumber>
        <email>lewishamilton@gmail.com</email>
    </contacts>
    <members>
        <member>
            <name>
                <firstName>Lewis</firstName>
                <lastName>Hamilton</lastName>
            </name>
            <birthdayDate format="yyyy-mm-dd">1988-01-14</birthdayDate>
            <genre>masculine</genre>
        </member>
        <member>
            <name>
                <firstName>Robbie</firstName>
                <lastName>Hamilton</lastName>
            </name>
            <birthdayDate format="yyyy-mm-dd">1990-07-14</birthdayDate>
            <genre>feminine</genre>
        </member>
    </members>
    <datePreferences>
        <datePreference format="yyyy-mm-dd">2021-12-07</datePreference> 
        <datePreference format="yyyy-mm-dd">2021-12-08</datePreference> 
        <datePreference format="yyyy-mm-dd">2021-12-10</datePreference> 
    </datePreferences>
</family>
